name: CI

on:
  push:

permissions: 
  contents: read
  packages: write

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login ghcr
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: install dependencies
        run: npm ci

      - name: run lint
        run: npm run lint
      
      - name: build
        run: npm run build

      - name: créer une image docker
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: push l'image créer dans ghcr
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }} 
