name: CI

on:
  push:

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: dire bonjour
        run: echo "bonjour"

      - name: dire CI en cours
        run: echo "CI en cours"